trigger:
  branches:
    include:
      - main
  tags:
    include:
    - v*
  paths:
    exclude:
      - README.md

resources:
  repositories:
    - repository: ci-cd
      name: devops/ci-cd
      type: git
      ref: pipes
extends:
  template: obase-etailer/campaign-optimization-ui/.build-ci.yaml@ci-cd

